version: '3.1'

services:
  localstack:
    image: localstack/localstack:0.14.5
    restart: always
    ports:
      - "4566-4583:4566-4583"
    environment:
      - REGION=eu-central-1
      - AWS_DEFAULT_REGION=eu-central-1
      - DEFAULT_REGION=eu-central-1
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - DOCKER_HOST=${LOCALSTACK_DOCKER_HOST-unix:///var/run/docker.sock}